[package]
name = "committee"
description = "autonomous proposal screening"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "5.7.0", features = ["schemars"] }
schemars = { version = "0.8" }
serde_json = "1.0.135"
serde = "1.0.217"
# - dcap-qvl (TEE verification)
# - sha2 (crypto)
# - hex (used with TEE)

[dev-dependencies]
near-sdk = { version = "5.7.0", features = ["unit-testing"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true